---
kind: pipeline
type: kubernetes
name: cypress

steps:
  - name: frontend
    image: node:erbium
    commands:
      - apt-get update && apt-get install --no-install-recommends -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb && rm -rf /var/lib/apt/lists/*
      - npm i
      - npm ci
      - npm run cy:run
  - name: Send Report
    image: node:dubnium-alpine3.11
    commands:
      - ls -l
      - node ./reporters/lippia-reporter/lippia-upload-report.js 
    when:
      status:
      - failure
      - success
      
trigger:
  event:
    - push
